### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [romance939913/cache-out#1]
- [x] Contains correct datatypes 
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null 
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [ ] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and back_ticked

**Comment by linakherchi** [comment]
Thank you Brennan !

Please refer to the checklist to appropriately modify your database schema

**Comment by romance939913** [comment]
This better?

**Comment by linakherchi** [comment]
What is the difference between holdings and watchlists ? 

I am checking your checklist to make sure that your database schema is presented correctly. Thank you

**Comment by linakherchi** [comment]
Table names should be bolded and have a bigger font size.
The foreign keys in the bullet points are to be back ticked, and not the 'foreign key' in the details column

**Comment by romance939913** [comment]
Users don't own shares of companies on their watchlist, they just watch them. However, they do own shares of companies in their holdings table, why that table contains total_shares. Also fixed the formatting.
